config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require './config/categories' 

  def index
    sort_by = params[:sort_by]
    @category = params[:category] 

    client = FreeToGameClient.new

    if sort_by.present?
      @games = client.games_by_sort(sort_by)  
    elsif @category.present?
      @games = client.games_by_category(@category) 
    else
      @games = client.games 
    end

  rescue => e
    Rails.logger.error "An error occurred while fetching games: #{e.message}"
    flash[:error] = "An error occurred while fetching games. Please try again later."
    @games = []
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Free To Play Games</h1>
<div class="main-container">
  <div class="game-list-container">
    <h2>
      <% if @category.present? %>
         <%= @category.split('-').map(&:capitalize).join(' ') %> (<%= @games.count %>)
      <% else %> 
        Free Games (<%= @games.count %>)
      <% end %>
      <% if params[:sort_by].present? %>
        (Sorted by: <%= params[:sort_by] %>)
      <% end %>
    </h2>

    <% if @games.any? %>
      <ul class="game-list">
        <% sorted_games = @games %>
        <% if params[:sort_by] == "release-date" %>
          <% sorted_games = @games.sort_by { |game| game["release_date"] } %>
        <% elsif params[:sort_by] == "alphabetical" %>
          <% sorted_games = @games.sort_by { |game| game["title"] } %>
        <% end %>
        
        <% sorted_games.each do |game| %>
          <li>
            <h2><%= game["title"] %></h2>
            <img src="<%= game["thumbnail"] %>" alt="<%= game["title"] %> Thumbnail">
            <p><%= game["short_description"] %></p>
            <p>Publisher: <%= game["publisher"] %></p>
            <p>Developer: <%= game["developer"] %></p>
            <p>Release Date: <%= game["release_date"] %></p>
            <p>Game Profile URL: <%= game["freetogame_profile_url"] %></p>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No games found.</p>
    <% end %>
  </div>

  <div class="filter-form-container">
    <h2>Filter Games</h2>
    <div class="filter-options">
      <%= form_tag("/games", method: "get") do %>
        <label for="category">Genre:</label>
        <select name="category" id="category">
          <% CATEGORIES.each do |category_name, category_value| %>
            <option value="<%= category_value %>"><%= category_name %></option>
          <% end %>
        </select>

        <button type="submit">Filter by Genre</button>
      <% end %>

      <%= form_tag("/games", method: "get") do %>
        <label for="sort_by">Sort By:</label>
        <select name="sort_by" id="sort_by">
          <option value="">None</option>
          <option value="release-date">Release Date</option>
          <option value="alphabetical">Alphabetical</option>
          <option value="popularity">Popularity</option>
        </select>

        <button type="submit">Sort Games</button>
      <% end %>

      <button><%= link_to "View All Games", games_path %></button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiWrapper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>